name: CI

on:
  - push

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} / ${{ matrix.pip-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Windows
        python-version:
          - pypy3
          - pypy2
        pip-version:
          - "latest"
          - "previous"

    env:
      TOXENV: pip${{ matrix.pip-version }}-coverage
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }} from GitHub
        if: "!endsWith(matrix.python-version, '-dev')"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python ${{ matrix.python-version }} from deadsnakes
        if: endsWith(matrix.python-version, '-dev')
        uses: deadsnakes/action@v2.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Log python version info (${{ matrix.python-version }})
        run: python --version --version
      - name: Install test dependencies
        run: python -m pip install -U tox virtualenv
      - name: Prepare test environment
        run: tox --notest -p auto --parallel-live
      - name: Test pip ${{ matrix.pip-version }}
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pip-version }}
